# wrangler.toml
name = 'vp2'
main = "_worker.js"
compatibility_date = "2024-04-28"
usage_model = "bundled"
workers_dev = true
v_namespaces = [
  { binding = "kv", id = "a2dd793c12984d3ca389e54ea0e5d04b" }
]

[vars]
FALLBACK = "https://p.yimo.qzz.io/"
TR_PASS = "2827659342"
UUID = "ba01b205-b522-4213-9383-4030975d1481"
